#!/bin/zsh

if [[ $1 == "" ]]; then
    echo "Usage: $0 <testname>"
    exit 1
fi

./generate_library.py

python $1 > res
./pyjs.py -I $1 > 1

while true; do
    ./generate_library.py
    if js 1 > 2; then
        if diff -u res 2; then
            echo "Files now match!"
            exit
        fi
    else
        echo "Could not run $1:"
        cat 2
    fi
    read "dummy?Press enter to continue>"
done